config/routes.rb
# Redmine - project management software
# Copyright (C) 2006-2012  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

RedmineApp::Application.routes.draw do

  root :to => 'welcome#index', :as => 'home'

  match 'login', :to => 'account#login', :as => 'signin'
  match 'logout', :to => 'account#logout', :as => 'signout'
  match 'account/register', :to => 'account#register', :via => [:get, :post], :as => 'register'
  match 'account/lost_password', :to => 'account#lost_password', :via => [:get, :post], :as => 'lost_password'
  match 'account/activate', :to => 'account#activate', :via => :get

  match '/news/preview', :controller => 'previews', :action => 'news', :as => 'preview_news'
  match '/issues/preview/new/:project_id', :to => 'previews#issue', :as => 'preview_new_issue'
  match '/issues/preview/edit/:id', :to => 'previews#issue', :as => 'preview_edit_issue'
  match '/issues/preview', :to => 'previews#issue', :as => 'preview_issue'

  match 'projects/:id/wiki', :to => 'wikis#edit', :via => :post
  match 'projects/:id/wiki/destroy', :to => 'wikis#destroy', :via => [:get, :post]

  match 'boards/:board_id/topics/new', :to => 'messages#new', :via => [:get, :post]
  get 'boards/:board_id/topics/:id', :to => 'messages#show', :as => 'board_message'
  match 'boards/:board_id/topics/quote/:id', :to => 'messages#quote', :via => [:get, :post]
  get 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'

  post 'boards/:board_id/topics/preview', :to => 'messages#preview'
  post 'boards/:board_id/topics/:id/replies', :to => 'messages#reply'
  post 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'
  post 'boards/:board_id/topics/:id/destroy', :to => 'messages#destroy'

  # Misc issue routes. TODO: move into resources
  match '/issues/auto_complete', :to => 'auto_completes#issues', :via => :get, :as => 'auto_complete_issues'
  match '/issues/context_menu', :to => 'context_menus#issues', :as => 'issues_context_menu'
  match '/issues/changes', :to => 'journals#index', :as => 'issue_changes'
  match '/issues/:id/quoted', :to => 'journals#new', :id => /\d+/, :via => :post, :as => 'quoted_issue'

  match '/journals/diff/:id', :to => 'journals#diff', :id => /\d+/, :via => :get
  match '/journals/edit/:id', :to => 'journals#edit', :id => /\d+/, :via => [:get, :post]

  match '/projects/:project_id/issues/gantt', :to => 'gantts#show'
  match '/issues/gantt', :to => 'gantts#show'

  match '/projects/:project_id/issues/calendar', :to => 'calendars#show'
  match '/issues/calendar', :to => 'calendars#show'

  match 'projects/:id/issues/report', :to => 'reports#issue_report', :via => :get
  match 'projects/:id/issues/report/:detail', :to => 'reports#issue_report_details', :via => :get

  match 'my/account', :controller => 'my', :action => 'account', :via => [:get, :post]
  match 'my/account/destroy', :controller => 'my', :action => 'destroy', :via => [:get, :post]
  match 'my/page', :controller => 'my', :action => 'page', :via => :get
  match 'my', :controller => 'my', :action => 'index', :via => :get # Redirects to my/page
  match 'my/reset_rss_key', :controller => 'my', :action => 'reset_rss_key', :via => :post
  match 'my/reset_api_key', :controller => 'my', :action => 'reset_api_key', :via => :post
  match 'my/password', :controller => 'my', :action => 'password', :via => [:get, :post]
  match 'my/page_layout', :controller => 'my', :action => 'page_layout', :via => :get
  match 'my/add_block', :controller => 'my', :action => 'add_block', :via => :post
  match 'my/remove_block', :controller => 'my', :action => 'remove_block', :via => :post
  match 'my/order_blocks', :controller => 'my', :action => 'order_blocks', :via => :post

  resources :users
  match 'users/:id/memberships/:membership_id', :to => 'users#edit_membership', :via => :put, :as => 'user_membership'
  match 'users/:id/memberships/:membership_id', :to => 'users#destroy_membership', :via => :delete
  match 'users/:id/memberships', :to => 'users#edit_membership', :via => :post, :as => 'user_memberships'

  match 'watchers/new', :controller=> 'watchers', :action => 'new', :via => :get
  match 'watchers', :controller=> 'watchers', :action => 'create', :via => :post
  match 'watchers/append', :controller=> 'watchers', :action => 'append', :via => :post
  match 'watchers/destroy', :controller=> 'watchers', :action => 'destroy', :via => :post
  match 'watchers/watch', :controller=> 'watchers', :action => 'watch', :via => :post
  match 'watchers/unwatch', :controller=> 'watchers', :action => 'unwatch', :via => :post
  match 'watchers/autocomplete_for_user', :controller=> 'watchers', :action => 'autocomplete_for_user', :via => :get

  match 'projects/:id/settings/:tab', :to => "projects#settings"

  resources :projects do
    member do
      get 'settings'
      post 'modules'
      post 'archive'
      post 'unarchive'
      post 'close'
      post 'reopen'
      match 'copy', :via => [:get, :post]
    end
    resources :departments, :only => [:edit, :new, :create,:destroy,:update,:show]

    resources :department_members do
      collection do
        get 'autocomplete'
      end
    end

    resources :performances do
      collection do
        get 'down'
        get 'export_excels'
        post 'send_excels'
      end
    end
    resources :performance_subjects

    resources :memberships, :shallow => true, :controller => 'members', :only => [:index, :show, :new, :create, :update, :destroy] do
      collection do
        get 'autocomplete'
      end
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    match 'issues/:copy_from/copy', :to => 'issues#new'
    resources :issues, :only => [:index, :new, :create] do
      resources :time_entries, :controller => 'timelog' do
        collection do
          get 'report'
        end
      end
    end
    # issue form update
    match 'issues/new', :controller => 'issues', :action => 'new', :via => [:put, :post], :as => 'issue_form'

    resources :files, :only => [:index, :new, :create]

    resources :versions, :except => [:index, :show, :edit, :update, :destroy] do
      collection do
        put 'close_completed'
      end
    end
    match 'versions.:format', :to => 'versions#index'
    match 'roadmap', :to => 'versions#index', :format => false
    match 'versions', :to => 'versions#index'

    resources :news, :except => [:show, :edit, :update, :destroy]
    resources :time_entries, :controller => 'timelog' do
      get 'report', :on => :collection
    end
    resources :queries, :only => [:new, :create]
    resources :issue_categories, :shallow => true
    resources :documents, :except => [:show, :edit, :update, :destroy]
    resources :boards
    resources :repositories, :shallow => true, :except => [:index, :show] do
      member do
        match 'committers', :via => [:get, :post]
      end
    end

    match 'wiki/index', :controller => 'wiki', :action => 'index', :via => :get
    resources :wiki, :except => [:index, :new, :create] do
      member do
        get 'rename'
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
      end
    end
    match 'wiki', :controller => 'wiki', :action => 'show', :via => :get
    get 'wiki/:id/:version', :to => 'wiki#show'
    delete 'wiki/:id/:version', :to => 'wiki#destroy_version'
    get 'wiki/:id/:version/annotate', :to => 'wiki#annotate'
    get 'wiki/:id/:version/diff', :to => 'wiki#diff'
  end

  resources :issues do
    collection do
      match 'bulk_edit', :via => [:get, :post]
      post 'bulk_update'
    end
    resources :time_entries, :controller => 'timelog' do
      collection do
        get 'report'
      end
    end
    resources :relations, :shallow => true, :controller => 'issue_relations', :only => [:index, :show, :create, :destroy]
  end
  match '/issues', :controller => 'issues', :action => 'destroy', :via => :delete

  resources :queries, :except => [:show]

  resources :news, :only => [:index, :show, :edit, :update, :destroy]
  match '/news/:id/comments', :to => 'comments#create', :via => :post
  match '/news/:id/comments/:comment_id', :to => 'comments#destroy', :via => :delete

  resources :versions, :only => [:show, :edit, :update, :destroy] do
    post 'status_by', :on => :member
  end

  resources :documents, :only => [:show, :edit, :update, :destroy] do
    post 'add_attachment', :on => :member
  end

  match '/time_entries/context_menu', :to => 'context_menus#time_entries', :as => :time_entries_context_menu

  resources :time_entries, :controller => 'timelog', :except => :destroy do
    collection do
      get 'report'
      get 'bulk_edit'
      post 'bulk_update'
    end
  end
  match '/time_entries/:id', :to => 'timelog#destroy', :via => :delete, :id => /\d+/
  # TODO: delete /time_entries for bulk deletion
  match '/time_entries/destroy', :to => 'timelog#destroy', :via => :delete

  # TODO: port to be part of the resources route(s)
  match 'projects/:id/settings/:tab', :to => 'projects#settings', :via => :get

  get 'projects/:id/activity', :to => 'activities#index'
  get 'projects/:id/activity.:format', :to => 'activities#index'

app/models/department_member.rb
class DepartmentMember < ActiveRecord::Base
  include Redmine::SafeAttributes
  belongs_to :department
  belongs_to :user, :foreign_key => 'user_id'
  has_many :performances, :dependent => :destroy, :foreign_key =>'department_member_id'

  safe_attributes 'user_id', 'department_id'
end

app/controllers/department_members_controller.rb
#encoding:utf-8
class DepartmentMembersController < ApplicationController
  # GET /department_members
  # GET /department_members.json

  menu_item :settings
  before_filter :find_project_by_project_id, :authorize
  helper :sort
  include SortHelper
  helper :watchers
  helper :Departments
  def index
  end

  # GET /department_members/1
  # GET /department_members/1.json
  def show
    @department = Department.find(params[:department_id])
    respond_to do |format|
      format.html {
        @members_count = @department.department_members.count
        @members_pages = Paginator.new self, @members_count, per_page_option, params['page']
        @members =  @department.department_members.all(
            :limit  =>  @members_pages.items_per_page,
            :offset =>  @members_pages.current.offset)
        @member ||=  @department.department_members.new
        render :action => 'show', :layout => !request.xhr?
      }
    end
  end

  # GET /department_members/new
  # GET /department_members/new.json
  def new
  end

  # GET /department_members/1/edit
  def edit
  end

  # POST /department_members
  # POST /department_members.json
  def create
    members = []
    @created = false
    @department = Department.find(params[:department_id])
    if params[:members]
      if params[:members][:user_ids] && !@department.blank?
        attrs = params[:members].dup
        user_ids = attrs.delete(:user_ids)
        user_ids.each do |user_id|
          members << DepartmentMember.new(:user_id => user_id, :department_id =>params[:department_id],:leader=>params[:leader])
        end
        @department.department_members << members
        @created = true
      end
    end

    respond_to do |format|
      format.js {
        @created
        @department
        @members_count = @department.department_members.count
        @members_pages = Paginator.new self, @members_count, per_page_option, params['page']
        @members =  @department.department_members.all(
            :limit  =>  @members_pages.items_per_page,
            :offset =>  @members_pages.current.offset)
        @member ||=  @department.department_members.new
      }
    end
  end

  # PUT /department_members/1
  # PUT /department_members/1.json
  def update
    @department_member = DepartmentMember.find(params[:id])
    updated = @department_member.update_attributes(params[:department_member])
    @department = @department_member.department
    @members = @department.department_members
    respond_to do |format|
      format.js
      format.api {
        if updated
          render_api_ok
        else
          render_validation_errors(@department_member)
        end
      }
    end
  end

  # DELETE /department_members/1
  # DELETE /department_members/1.json
  def destroy
    @department_member = DepartmentMember.find(params[:id])
    @department = Department.find(@department_member.department_id)
    params[:department_id] = @department_member.department_id
    @member ||=  @department.department_members.new
    @members_count = @department.department_members.count
    @members_pages = Paginator.new self, @members_count, per_page_option, params['page']
    @members =  @department.department_members.all(
        :limit  =>  @members_pages.items_per_page,
        :offset =>  @members_pages.current.offset)
    @members =  @department.department_members
    if request.delete?
      @department_member.destroy
    end
    respond_to do |format|
        format.js
     end
  end

  def autocomplete
    @principals = Principal.active.not_member_of_department(@project).like(params[:q]).all(:limit => 100)
    render :layout => false
  end
end

app/helpers/department_members_helper.rb
module DepartmentMembersHelper
end

app/views/department_members/_form.html.erb
<%= form_for(@department_member) do |f| %>
  <% if @department_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department_member.errors.count, "error") %> prohibited this department_member from being saved:</h2>

      <ul>
      <% @department_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :department_id %><br />
    <%= f.number_field :department_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :leader %><br />
    <%= f.check_box :leader %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/department_members/_list.html.erb
#encoding:utf-8
<% if performances.any? %>
    <table class="list members">
      <thead><tr>
        <th style = "text-align: left">#</th>
        <th style = "text-align: left">状态</th>
        <th style = "text-align: left">部门</th>
        <th style = "text-align: left">月份</th>
        <th style= "text-align: left">成员</th>
        <th style= "text-align: left">自我评价</th>
        <th style= "text-align: left">主管评价</th>
        <th style= "text-align: left">自评分</th>
        <th style= "text-align: left">主管评分</th>
        <th style= "text-align: left">主管评级</th>
        <th>操作</th>
      </tr></thead>
      <tbody>
      <% performances.each do |dep| %>
          <tr id="member-1" class="<%= cycle 'odd', 'even' %> member">
            <td><%= dep.id %></td>
            <td><%= get_performance_status dep %></td>
            <td><%= get_performance_department_name(dep) %></td>
            <td><%= get_performance_date_month dep %></td>
            <td><%= get_performance_user_name dep.user_id %></td>
            <td><%= get_text_limit dep.self_assessment %></td>
            <td><%= get_text_limit dep.leader_assessment %></td>
            <td><%= dep.self_mark.blank? ? "暂无评分": dep.self_mark %></td>
            <td><%= dep.leader_mark.blank? ? "暂无评分": dep.leader_mark %></td>
            <td><%= get_performance_rating dep %></td>
            <td class="buttons">
              <a class = "icon icon-show" rel="nofollow" href =<%= "#" %>>查看</a>
              <a class="icon icon-edit" rel="nofollow" href =<%="#" %>>编辑</a>
            </td>
          </tr>
      <% end; reset_cycle %>
      </tbody>
    </table>
<% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/department_members/_members.html.erb
#encoding:utf-8
<h2 class="icon icon-dept1"> <%=h @department.name %></h2>
<div class="tab-content" id="tab-content-members">
  <%= error_messages_for 'member' %>
  <% members = @members%>

  <div class="splitcontentleft">
    <% if @members.any? %>
        <table class="list members">
          <thead><tr>
            <th><%= l(:label_member) %> </th>
            <th><%= l(:field_leader) %></th>
            <th style="width:25%"></th>
          </tr></thead>
          <tbody>
          <% @members.each do |member| %>
              <% next if member.new_record? %>
              <tr id="member-<%= member.id %>" class="<%= cycle 'odd', 'even' %> member">
                <td  align="center" class="users"><span  <%=sanitize user_is_leader?(member) ? "class= 'icon icon-style icon-leader'" : "class= 'icon icon-style icon-normal-user'" %> ><%= get_user_full_name(member) %></span ></td>
                <td  align="center" class="roles">
                <span id="member-<%= member.id %>-ranks" >
                  <span id="member-<%= member.id %>-ranks-img"  style = "display: <%= user_is_leader?(member) ? 'inline' : 'none' %>"><%= checked_image %></span>
                </span>
                  <%= form_for(member, {:remote => true, :url =>project_department_member_path(@project,member) ,
                                        :method => :put,
                                        :html => { :id => "member-#{member.id}-ranks-form", :class => 'hol' }}
                      ) do |f| %>
                      <% ranks = rank_radio_button_for_select(member) %>
                      <p> <% ranks.each do |rank| %>
                            <label><%= f.radio_button :leader, rank[:id],:checked=>rank[:checked]%> <%= rank[:name] %></label>&nbsp;&nbsp;&nbsp;
                        <% end %></p>
                      <p><%= submit_tag l(:button_change), :class => "small" %>
                        <%= link_to_function l(:button_cancel),
                                             "$('#member-#{member.id}-ranks').show(); $('#member-#{member.id}-ranks-form').hide(); return false;"
                        %></p>
                  <% end %>
                </td>
                <td class="buttons">
                  <%= link_to_function l(:button_edit),
                                       "$('#member-#{member.id}-ranks').hide(); $('#member-#{member.id}-ranks-form').show(); return false;",
                                       :class => 'icon icon-edit' %>
                  <%= delete_link project_department_member_path(@project,member),
                                  :remote => true  %>
                </td>

              </tr>
          <% end; reset_cycle %>
          </tbody>
        </table>
        <p class="pagination"><%= pagination_links_full @members_pages, @members_count %></p>
    <% else %>
        <p class="nodata"><%= l(:label_no_data) %></p>
    <% end %>
    <%= link_to l(:button_back), settings_project_path(@project, :tab => 'departments') %>
  </div>

  <% principals = Principal.active.not_member_of_department(@project,@department).all(:limit => 100, :order => 'type, login, lastname ASC') %>

  <div class="splitcontentright">
    <% ranks = rank_radio_button_for_select(nil) %>
    <% if ranks.any? && principals.any? %>
        <%= form_for(@member, {:url => project_department_members_path(@project,@member), :remote => true, :method => :post}) do |f| %>
            <fieldset><legend><%=l(:label_member_new)%></legend>
              <p><%= label_tag "principal_search", l(:label_principal_search) %><%= text_field_tag 'principal_search', nil %></p>
              <%= javascript_tag "observeSearchfield('principal_search', 'principals', '#{ escape_javascript autocomplete_project_department_members_path(@project) }')" %>

              <div id="principals">
                <%= principals_check_box_tags 'members[user_ids][]', principals %>
              </div>
              <%= hidden_field_tag :department_id, params[:department_id] %>
              <p><%= l(:label_role_plural) %>:
                <% ranks.each do |rank| %>
                    <label><%= radio_button_tag 'leader', rank[:id], rank[:checked] %> <%= rank[:name] %></label>
                <% end %></p>
              <p><%= submit_tag l(:button_add), :id => 'member-add-submit' %></p>
            </fieldset>
        <% end %>
    <% end %>
  </div>
</div>

app/views/department_members/autocomplete.html.erb
<%= principals_check_box_tags 'members[user_ids][]', @principals %>

app/views/department_members/create.js.erb
//encoding:utf-8
$('#tab-department-members').html('<%= escape_javascript(render :partial => 'department_members/members') %>');
hideOnLoad();

<% if @created %>
  $("#member-<%= @members.last.id%>").effect("highlight");
<% else %>
  alert('<%= raw(escape_javascript(l(:notice_failed_to_save_members, :errors => "无效添加"))) %>');
<% end %>

app/views/department_members/destroy.js.erb
$('#tab-department-members').html('<%= escape_javascript(render :partial => 'department_members/members') %>');
hideOnLoad();

app/views/department_members/new.html.erb
<h1>New department_member</h1>

<%= render 'form' %>

<%= link_to 'Back', department_members_path %>

app/views/department_members/show.html.erb
#encoding:utf-8
<div id="tab-department-members">
    <%= render 'members' %>
</div>

app/views/department_members/update.js.erb
<% if !@department_member.leader %>
   //$("#member-<%= @department_member.id %>-ranks").hide();
   $("#member-<%= @department_member.id %>-ranks-img").hide();
   //$("#member-<%= @department_member.id %>-ranks-img > img").hide();
<% else %>
  $("#member-<%= @department_member.id %>-ranks").show();
  $("#member-<%= @department_member.id %>-ranks-img").show();
//$("#member-<%= @department_member.id %>-ranks-img > img").show();
<% end %>
hideOnLoad();
$("#member-<%= @department_member.id %>").effect("highlight");